---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-router
  labels:
    app: wordpress-router
spec:
  ports:
    - port: 80
  selector:
    app: wordpress-router
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-router
  labels:
    app: wordpress-router
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-router
    spec:
      containers:
      - name: mysqlrouter
        image: mysql/mysql-router:8.0.12
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-mysql-root-password
              key: password
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_HOST
          value: mysql-wordpress-0.mysql-wordpress
        - name: MYSQL_INNODB_NUM_MEMBERS
          value: "3"
        command:
        - "/bin/bash"
        - "-cx"
        - "exec /run.sh mysqlrouter"
      - name: wordpress
        image: wordpress:4.9-php7.2-apache
        env:
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1:6446
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-mysql-root-password
              key: password
        ports:
        - containerPort: 80
