apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator
  namespace: {{ if .Values.operator.global }}{{ .Release.Namespace }}{{ else }}{{ .Values.operator.namespace}}{{ end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-agent
  namespace: {{ if .Values.operator.global }}{{ .Release.Namespace }}{{ else }}{{ .Values.operator.namespace}}{{ end }}

{{- if .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: {{ if .Values.operator.global }}Cluster{{ end }}Role
metadata:
  name: mysql-operator
  namespace: {{ default .Release.Namespace .Values.operator.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
    - create

  - apiGroups: [""]
    resources:
    - services
    verbs:
    - create
    - get
    - list
    - watch

  - apiGroups: [""]
    resources: ["events"]
    verbs:
    - create
    - update
    - patch

  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: ["mysql.oracle.com"]
    resources:
    - mysqlbackups
    - mysqlbackupschedules
    - mysqlclusters
    - mysqlrestores
    verbs:
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: ["mysql.oracle.com"]
    resources: ["mysqlbackups"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: {{ if .Values.operator.global }}Cluster{{ end }}RoleBinding
metadata:
  name: mysql-operator
  namespace: {{ default .Release.Namespace .Values.operator.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if .Values.operator.global }}Cluster{{ end }}Role
  name: mysql-operator
subjects:
- kind: ServiceAccount
  name: mysql-operator
  namespace: {{ default .Release.Namespace .Values.operator.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: {{ if .Values.operator.global }}Cluster{{ end }}Role
metadata:
  name: mysql-agent
  namespace: {{ default .Release.Namespace .Values.operator.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["events"]
    verbs:
    - create
    - update
    - patch

  - apiGroups: ["mysql.oracle.com"]
    resources:
    - mysqlbackups
    - mysqlbackupschedules
    - mysqlclusters
    - mysqlrestores
    verbs:
    - get
    - list
    - patch
    - update
    - watch

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: {{ if .Values.operator.global }}Cluster{{ end }}RoleBinding
metadata:
  name: mysql-agent
  namespace: {{ default .Release.Namespace .Values.operator.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:  {{ if .Values.operator.global }}Cluster{{ end }}Role
  name: mysql-agent
subjects:
- kind: ServiceAccount
  name: mysql-agent
  namespace: {{ default .Release.Namespace .Values.operator.namespace }}
{{ end }}