---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator
  namespace: {{ if .Values.operator.global }}mysql-operator{{ else }}{{ .Values.operator.namespace}}{{ end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-agent
  namespace: {{ if .Values.operator.global }}default{{ else }}{{ .Values.operator.namespace}}{{ end }}
---
{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: {{ if .Values.operator.global }}Cluster{{ end }}Role
metadata:
  name: mysql-operator{{ if .Values.operator.global }}{{ else}}
  namespace: {{ .Values.operator.namespace}}{{ end }}
rules:
  - apiGroups:
    - mysql.oracle.com
    resources:
    - mysqlclusters
    - mysqlbackups
    - mysqlbackupschedules
    - mysqlrestores
    verbs: ["*"]
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - create
    - delete
  - apiGroups:
    - apps
    resources:
    - statefulsets
    verbs:
    - get
    - list
    - watch
    - patch
    - create
    - update
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - update
    - patch
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - get
    - list
    - watch
    - create
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: {{ if .Values.operator.global }}Cluster{{ end }}RoleBinding
metadata:
  name: mysql-operator
  namespace: {{ .Values.operator.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:  {{ if .Values.operator.global }}Cluster{{ end }}Role
  name: mysql-operator
subjects:
- kind: ServiceAccount
  name: mysql-operator
  namespace: {{ .Values.operator.namespace }}
---
kind: {{ if .Values.operator.global }}Cluster{{ end }}RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mysql-agent
  namespace: {{ if .Values.operator.global }}default{{ else }}{{ .Values.operator.namespace }}{{ end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if .Values.operator.global }}Cluster{{ end }}Role
  name: mysql-operator
subjects:
- kind: ServiceAccount
  name: mysql-agent
  namespace: {{ if .Values.operator.global }}default{{ else }}{{ .Values.operator.namespace }}{{ end }}
{{- end }}
