---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator
  namespace: {{ if and (.Values.operator.global) (eq .Values.operator.namespace "mysql-operator") }}mysql-operator{{ else }}{{ .Values.operator.namespace}}{{ end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-agent
  namespace: {{ if and (.Values.operator.global) (eq .Values.operator.namespace "mysql-operator") }}default{{ else }}{{ .Values.operator.namespace}}{{ end }}

---
{{- if .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: {{ if and (.Values.operator.global) (eq .Values.operator.namespace "mysql-operator") }}Cluster{{ end }}Role
metadata:
  name: mysql-operator{{ if and (.Values.operator.global) (eq .Values.operator.namespace "mysql-operator") }}{{ else}}
  namespace: {{ .Values.operator.namespace}}{{ end }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      {{- if hasPrefix "0.1" .Values.image.tag }}
      - get
      {{- end}}
      - create

  - apiGroups: [""]
    resources:
    - services
    {{- if hasPrefix "0.1" .Values.image.tag }}
    - configmaps
    {{- end }}
    verbs:
    - create
    - get
    - list
    - watch

  - apiGroups: [""]
    resources: ["events"]
    verbs:
    - create
    - update
    - patch

  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: ["mysql.oracle.com"]
    resources:
    - mysqlbackups
    - mysqlbackupschedules
    - mysqlclusters
    - mysqlclusters/finalizers
    - mysqlrestores
    verbs:
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: ["mysql.oracle.com"]
    resources: ["mysqlbackups"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: {{ if and (.Values.operator.global) (eq .Values.operator.namespace "mysql-operator") }}Cluster{{ end }}Role
metadata:
  name: mysql-agent{{ if and (.Values.operator.global) (eq .Values.operator.namespace "mysql-operator") }}{{ else}}
  namespace: {{ .Values.operator.namespace}}{{ end }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["events"]
    verbs:
    - create
    - update
    - patch

  - apiGroups: ["mysql.oracle.com"]
    resources:
    - mysqlbackups
    - mysqlbackupschedules
    - mysqlclusters
    - mysqlclusters/finalizers
    - mysqlrestores
    verbs:
    - get
    - list
    - patch
    - update
    - watch

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind:  {{ if and (.Values.operator.global) (eq .Values.operator.namespace "mysql-operator") }}Cluster{{ end }}RoleBinding
metadata:
  name: mysql-operator
  namespace: {{ .Values.operator.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:  {{ if and (.Values.operator.global) (eq .Values.operator.namespace "mysql-operator") }}Cluster{{ end }}Role
  name: mysql-operator
subjects:
- kind: ServiceAccount
  name: mysql-operator
  namespace: {{ .Values.operator.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind:  {{ if and (.Values.operator.global) (eq .Values.operator.namespace "mysql-operator") }}Cluster{{ end }}RoleBinding
metadata:
  name: mysql-agent
  namespace: {{ .Values.operator.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:  {{ if and (.Values.operator.global) (eq .Values.operator.namespace "mysql-operator") }}Cluster{{ end }}Role
  name: mysql-agent
subjects:
- kind: ServiceAccount
  name: mysql-agent
  namespace: {{ .Values.operator.namespace }}
{{- end }}
