apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: mysql
spec:
  members: 1
  initContainers:
  - name: sleep
    image: busybox
    command:
    - echo
    - "This is first init container"
  - name: sleep
    image: busybox
    command:
    - echo
    - "This is second init container"
