# This example will create a MySQL cluster which persists data to an OCI Block Volume.
apiVersion: "mysql.oracle.com/v1"
kind: MySQLCluster
metadata:
  name: mysql
spec:
  replicas: 3
  volumeClaimTemplate:
    metadata:
      name: mysql-block-volume
    spec:
      storageClassName: "oci"
      selector:
        matchLabels:
          oci-availability-domain: "PHX-AD-1"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
