apiVersion: mysql.oracle.com/v1alpha1
kind: MySQLBackupSchedule
metadata:
  name: mysql-backup-schedule
spec:
  schedule: '30 * * * *'
  backupTemplate:
    executor:
      provider: mysqldump
      databases:
        - test
    storage:
      provider: s3
      secretRef:
        name: s3-credentials
      config:
        endpoint: ocitenancy.compat.objectstorage.ociregion.oraclecloud.com
        region: ociregion
        bucket: mybucket
    clusterRef:
      name: mysql
