apiVersion: mysql.oracle.com/v1
kind: MySQLBackup
metadata:
  name: mysql-backup
spec:
  executor:
    mysqldump:
      databases:
        - name: test
  storageProvider:
    s3:
      endpoint: ocitenancy.compat.objectstorage.ociregion.oraclecloud.com
      region:   ociregion
      bucket:   mybucket
      credentialsSecret:
        name: s3-credentials
  clusterRef:
    name: mysql
