// +build !ignore_autogenerated

// Copyright 2018 Oracle and/or its affiliates. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was autogenerated by defaulter-gen. Do not edit it manually!

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&MySQLBackup{}, func(obj interface{}) { SetObjectDefaults_MySQLBackup(obj.(*MySQLBackup)) })
	scheme.AddTypeDefaultingFunc(&MySQLBackupList{}, func(obj interface{}) { SetObjectDefaults_MySQLBackupList(obj.(*MySQLBackupList)) })
	scheme.AddTypeDefaultingFunc(&MySQLBackupSchedule{}, func(obj interface{}) { SetObjectDefaults_MySQLBackupSchedule(obj.(*MySQLBackupSchedule)) })
	scheme.AddTypeDefaultingFunc(&MySQLBackupScheduleList{}, func(obj interface{}) { SetObjectDefaults_MySQLBackupScheduleList(obj.(*MySQLBackupScheduleList)) })
	scheme.AddTypeDefaultingFunc(&MySQLCluster{}, func(obj interface{}) { SetObjectDefaults_MySQLCluster(obj.(*MySQLCluster)) })
	scheme.AddTypeDefaultingFunc(&MySQLClusterList{}, func(obj interface{}) { SetObjectDefaults_MySQLClusterList(obj.(*MySQLClusterList)) })
	scheme.AddTypeDefaultingFunc(&MySQLClusterStatus{}, func(obj interface{}) { SetObjectDefaults_MySQLClusterStatus(obj.(*MySQLClusterStatus)) })
	scheme.AddTypeDefaultingFunc(&MySQLRestore{}, func(obj interface{}) { SetObjectDefaults_MySQLRestore(obj.(*MySQLRestore)) })
	scheme.AddTypeDefaultingFunc(&MySQLRestoreList{}, func(obj interface{}) { SetObjectDefaults_MySQLRestoreList(obj.(*MySQLRestoreList)) })
	return nil
}

func SetObjectDefaults_MySQLBackup(in *MySQLBackup) {
	SetDefaults_BackupSpec(&in.Spec)
	SetDefaults_BackupStatus(&in.Status)
}

func SetObjectDefaults_MySQLBackupList(in *MySQLBackupList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_MySQLBackup(a)
	}
}

func SetObjectDefaults_MySQLBackupSchedule(in *MySQLBackupSchedule) {
	SetDefaults_BackupScheduleSpec(&in.Spec)
	SetDefaults_BackupSpec(&in.Spec.BackupTemplate)
	SetDefaults_ScheduleStatus(&in.Status)
}

func SetObjectDefaults_MySQLBackupScheduleList(in *MySQLBackupScheduleList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_MySQLBackupSchedule(a)
	}
}

func SetObjectDefaults_MySQLCluster(in *MySQLCluster) {
	SetDefaults_MySQLClusterSpec(&in.Spec)
	SetObjectDefaults_MySQLClusterStatus(&in.Status)
}

func SetObjectDefaults_MySQLClusterList(in *MySQLClusterList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_MySQLCluster(a)
	}
}

func SetObjectDefaults_MySQLClusterStatus(in *MySQLClusterStatus) {
	SetDefaults_MySQLClusterStatus(in)
}

func SetObjectDefaults_MySQLRestore(in *MySQLRestore) {
	SetDefaults_RestoreSpec(&in.Spec)
	SetDefaults_RestoreStatus(&in.Status)
}

func SetObjectDefaults_MySQLRestoreList(in *MySQLRestoreList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_MySQLRestore(a)
	}
}
