// +build !ignore_autogenerated

// Copyright 2018 Oracle and/or its affiliates. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1

import (
	unsafe "unsafe"

	mysql "github.com/oracle/mysql-operator/pkg/apis/mysql"
	core_v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1_BackupOutcome_To_mysql_BackupOutcome,
		Convert_mysql_BackupOutcome_To_v1_BackupOutcome,
		Convert_v1_BackupScheduleSpec_To_mysql_BackupScheduleSpec,
		Convert_mysql_BackupScheduleSpec_To_v1_BackupScheduleSpec,
		Convert_v1_BackupSpec_To_mysql_BackupSpec,
		Convert_mysql_BackupSpec_To_v1_BackupSpec,
		Convert_v1_BackupStatus_To_mysql_BackupStatus,
		Convert_mysql_BackupStatus_To_v1_BackupStatus,
		Convert_v1_Executor_To_mysql_Executor,
		Convert_mysql_Executor_To_v1_Executor,
		Convert_v1_MySQLBackup_To_mysql_MySQLBackup,
		Convert_mysql_MySQLBackup_To_v1_MySQLBackup,
		Convert_v1_MySQLBackupList_To_mysql_MySQLBackupList,
		Convert_mysql_MySQLBackupList_To_v1_MySQLBackupList,
		Convert_v1_MySQLBackupSchedule_To_mysql_MySQLBackupSchedule,
		Convert_mysql_MySQLBackupSchedule_To_v1_MySQLBackupSchedule,
		Convert_v1_MySQLBackupScheduleList_To_mysql_MySQLBackupScheduleList,
		Convert_mysql_MySQLBackupScheduleList_To_v1_MySQLBackupScheduleList,
		Convert_v1_MySQLCluster_To_mysql_MySQLCluster,
		Convert_mysql_MySQLCluster_To_v1_MySQLCluster,
		Convert_v1_MySQLClusterList_To_mysql_MySQLClusterList,
		Convert_mysql_MySQLClusterList_To_v1_MySQLClusterList,
		Convert_v1_MySQLClusterSpec_To_mysql_MySQLClusterSpec,
		Convert_mysql_MySQLClusterSpec_To_v1_MySQLClusterSpec,
		Convert_v1_MySQLClusterStatus_To_mysql_MySQLClusterStatus,
		Convert_mysql_MySQLClusterStatus_To_v1_MySQLClusterStatus,
		Convert_v1_MySQLRestore_To_mysql_MySQLRestore,
		Convert_mysql_MySQLRestore_To_v1_MySQLRestore,
		Convert_v1_MySQLRestoreList_To_mysql_MySQLRestoreList,
		Convert_mysql_MySQLRestoreList_To_v1_MySQLRestoreList,
		Convert_v1_RestoreSpec_To_mysql_RestoreSpec,
		Convert_mysql_RestoreSpec_To_v1_RestoreSpec,
		Convert_v1_RestoreStatus_To_mysql_RestoreStatus,
		Convert_mysql_RestoreStatus_To_v1_RestoreStatus,
		Convert_v1_ScheduleStatus_To_mysql_ScheduleStatus,
		Convert_mysql_ScheduleStatus_To_v1_ScheduleStatus,
		Convert_v1_Storage_To_mysql_Storage,
		Convert_mysql_Storage_To_v1_Storage,
	)
}

func autoConvert_v1_BackupOutcome_To_mysql_BackupOutcome(in *BackupOutcome, out *mysql.BackupOutcome, s conversion.Scope) error {
	out.Location = in.Location
	return nil
}

// Convert_v1_BackupOutcome_To_mysql_BackupOutcome is an autogenerated conversion function.
func Convert_v1_BackupOutcome_To_mysql_BackupOutcome(in *BackupOutcome, out *mysql.BackupOutcome, s conversion.Scope) error {
	return autoConvert_v1_BackupOutcome_To_mysql_BackupOutcome(in, out, s)
}

func autoConvert_mysql_BackupOutcome_To_v1_BackupOutcome(in *mysql.BackupOutcome, out *BackupOutcome, s conversion.Scope) error {
	out.Location = in.Location
	return nil
}

// Convert_mysql_BackupOutcome_To_v1_BackupOutcome is an autogenerated conversion function.
func Convert_mysql_BackupOutcome_To_v1_BackupOutcome(in *mysql.BackupOutcome, out *BackupOutcome, s conversion.Scope) error {
	return autoConvert_mysql_BackupOutcome_To_v1_BackupOutcome(in, out, s)
}

func autoConvert_v1_BackupScheduleSpec_To_mysql_BackupScheduleSpec(in *BackupScheduleSpec, out *mysql.BackupScheduleSpec, s conversion.Scope) error {
	out.Schedule = in.Schedule
	if err := Convert_v1_BackupSpec_To_mysql_BackupSpec(&in.BackupTemplate, &out.BackupTemplate, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_BackupScheduleSpec_To_mysql_BackupScheduleSpec is an autogenerated conversion function.
func Convert_v1_BackupScheduleSpec_To_mysql_BackupScheduleSpec(in *BackupScheduleSpec, out *mysql.BackupScheduleSpec, s conversion.Scope) error {
	return autoConvert_v1_BackupScheduleSpec_To_mysql_BackupScheduleSpec(in, out, s)
}

func autoConvert_mysql_BackupScheduleSpec_To_v1_BackupScheduleSpec(in *mysql.BackupScheduleSpec, out *BackupScheduleSpec, s conversion.Scope) error {
	out.Schedule = in.Schedule
	if err := Convert_mysql_BackupSpec_To_v1_BackupSpec(&in.BackupTemplate, &out.BackupTemplate, s); err != nil {
		return err
	}
	return nil
}

// Convert_mysql_BackupScheduleSpec_To_v1_BackupScheduleSpec is an autogenerated conversion function.
func Convert_mysql_BackupScheduleSpec_To_v1_BackupScheduleSpec(in *mysql.BackupScheduleSpec, out *BackupScheduleSpec, s conversion.Scope) error {
	return autoConvert_mysql_BackupScheduleSpec_To_v1_BackupScheduleSpec(in, out, s)
}

func autoConvert_v1_BackupSpec_To_mysql_BackupSpec(in *BackupSpec, out *mysql.BackupSpec, s conversion.Scope) error {
	out.Executor = (*mysql.Executor)(unsafe.Pointer(in.Executor))
	out.Storage = (*mysql.Storage)(unsafe.Pointer(in.Storage))
	out.ClusterRef = (*core_v1.LocalObjectReference)(unsafe.Pointer(in.ClusterRef))
	out.AgentScheduled = in.AgentScheduled
	return nil
}

// Convert_v1_BackupSpec_To_mysql_BackupSpec is an autogenerated conversion function.
func Convert_v1_BackupSpec_To_mysql_BackupSpec(in *BackupSpec, out *mysql.BackupSpec, s conversion.Scope) error {
	return autoConvert_v1_BackupSpec_To_mysql_BackupSpec(in, out, s)
}

func autoConvert_mysql_BackupSpec_To_v1_BackupSpec(in *mysql.BackupSpec, out *BackupSpec, s conversion.Scope) error {
	out.Executor = (*Executor)(unsafe.Pointer(in.Executor))
	out.Storage = (*Storage)(unsafe.Pointer(in.Storage))
	out.ClusterRef = (*core_v1.LocalObjectReference)(unsafe.Pointer(in.ClusterRef))
	out.AgentScheduled = in.AgentScheduled
	return nil
}

// Convert_mysql_BackupSpec_To_v1_BackupSpec is an autogenerated conversion function.
func Convert_mysql_BackupSpec_To_v1_BackupSpec(in *mysql.BackupSpec, out *BackupSpec, s conversion.Scope) error {
	return autoConvert_mysql_BackupSpec_To_v1_BackupSpec(in, out, s)
}

func autoConvert_v1_BackupStatus_To_mysql_BackupStatus(in *BackupStatus, out *mysql.BackupStatus, s conversion.Scope) error {
	out.Phase = mysql.BackupPhase(in.Phase)
	if err := Convert_v1_BackupOutcome_To_mysql_BackupOutcome(&in.Outcome, &out.Outcome, s); err != nil {
		return err
	}
	out.TimeStarted = in.TimeStarted
	out.TimeCompleted = in.TimeCompleted
	return nil
}

// Convert_v1_BackupStatus_To_mysql_BackupStatus is an autogenerated conversion function.
func Convert_v1_BackupStatus_To_mysql_BackupStatus(in *BackupStatus, out *mysql.BackupStatus, s conversion.Scope) error {
	return autoConvert_v1_BackupStatus_To_mysql_BackupStatus(in, out, s)
}

func autoConvert_mysql_BackupStatus_To_v1_BackupStatus(in *mysql.BackupStatus, out *BackupStatus, s conversion.Scope) error {
	out.Phase = BackupPhase(in.Phase)
	if err := Convert_mysql_BackupOutcome_To_v1_BackupOutcome(&in.Outcome, &out.Outcome, s); err != nil {
		return err
	}
	out.TimeStarted = in.TimeStarted
	out.TimeCompleted = in.TimeCompleted
	return nil
}

// Convert_mysql_BackupStatus_To_v1_BackupStatus is an autogenerated conversion function.
func Convert_mysql_BackupStatus_To_v1_BackupStatus(in *mysql.BackupStatus, out *BackupStatus, s conversion.Scope) error {
	return autoConvert_mysql_BackupStatus_To_v1_BackupStatus(in, out, s)
}

func autoConvert_v1_Executor_To_mysql_Executor(in *Executor, out *mysql.Executor, s conversion.Scope) error {
	out.Provider = in.Provider
	out.Databases = *(*[]string)(unsafe.Pointer(&in.Databases))
	return nil
}

// Convert_v1_Executor_To_mysql_Executor is an autogenerated conversion function.
func Convert_v1_Executor_To_mysql_Executor(in *Executor, out *mysql.Executor, s conversion.Scope) error {
	return autoConvert_v1_Executor_To_mysql_Executor(in, out, s)
}

func autoConvert_mysql_Executor_To_v1_Executor(in *mysql.Executor, out *Executor, s conversion.Scope) error {
	out.Provider = in.Provider
	out.Databases = *(*[]string)(unsafe.Pointer(&in.Databases))
	return nil
}

// Convert_mysql_Executor_To_v1_Executor is an autogenerated conversion function.
func Convert_mysql_Executor_To_v1_Executor(in *mysql.Executor, out *Executor, s conversion.Scope) error {
	return autoConvert_mysql_Executor_To_v1_Executor(in, out, s)
}

func autoConvert_v1_MySQLBackup_To_mysql_MySQLBackup(in *MySQLBackup, out *mysql.MySQLBackup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_BackupSpec_To_mysql_BackupSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_BackupStatus_To_mysql_BackupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_MySQLBackup_To_mysql_MySQLBackup is an autogenerated conversion function.
func Convert_v1_MySQLBackup_To_mysql_MySQLBackup(in *MySQLBackup, out *mysql.MySQLBackup, s conversion.Scope) error {
	return autoConvert_v1_MySQLBackup_To_mysql_MySQLBackup(in, out, s)
}

func autoConvert_mysql_MySQLBackup_To_v1_MySQLBackup(in *mysql.MySQLBackup, out *MySQLBackup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_mysql_BackupSpec_To_v1_BackupSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_mysql_BackupStatus_To_v1_BackupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_mysql_MySQLBackup_To_v1_MySQLBackup is an autogenerated conversion function.
func Convert_mysql_MySQLBackup_To_v1_MySQLBackup(in *mysql.MySQLBackup, out *MySQLBackup, s conversion.Scope) error {
	return autoConvert_mysql_MySQLBackup_To_v1_MySQLBackup(in, out, s)
}

func autoConvert_v1_MySQLBackupList_To_mysql_MySQLBackupList(in *MySQLBackupList, out *mysql.MySQLBackupList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]mysql.MySQLBackup)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_MySQLBackupList_To_mysql_MySQLBackupList is an autogenerated conversion function.
func Convert_v1_MySQLBackupList_To_mysql_MySQLBackupList(in *MySQLBackupList, out *mysql.MySQLBackupList, s conversion.Scope) error {
	return autoConvert_v1_MySQLBackupList_To_mysql_MySQLBackupList(in, out, s)
}

func autoConvert_mysql_MySQLBackupList_To_v1_MySQLBackupList(in *mysql.MySQLBackupList, out *MySQLBackupList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]MySQLBackup)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_mysql_MySQLBackupList_To_v1_MySQLBackupList is an autogenerated conversion function.
func Convert_mysql_MySQLBackupList_To_v1_MySQLBackupList(in *mysql.MySQLBackupList, out *MySQLBackupList, s conversion.Scope) error {
	return autoConvert_mysql_MySQLBackupList_To_v1_MySQLBackupList(in, out, s)
}

func autoConvert_v1_MySQLBackupSchedule_To_mysql_MySQLBackupSchedule(in *MySQLBackupSchedule, out *mysql.MySQLBackupSchedule, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_BackupScheduleSpec_To_mysql_BackupScheduleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_ScheduleStatus_To_mysql_ScheduleStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_MySQLBackupSchedule_To_mysql_MySQLBackupSchedule is an autogenerated conversion function.
func Convert_v1_MySQLBackupSchedule_To_mysql_MySQLBackupSchedule(in *MySQLBackupSchedule, out *mysql.MySQLBackupSchedule, s conversion.Scope) error {
	return autoConvert_v1_MySQLBackupSchedule_To_mysql_MySQLBackupSchedule(in, out, s)
}

func autoConvert_mysql_MySQLBackupSchedule_To_v1_MySQLBackupSchedule(in *mysql.MySQLBackupSchedule, out *MySQLBackupSchedule, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_mysql_BackupScheduleSpec_To_v1_BackupScheduleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_mysql_ScheduleStatus_To_v1_ScheduleStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_mysql_MySQLBackupSchedule_To_v1_MySQLBackupSchedule is an autogenerated conversion function.
func Convert_mysql_MySQLBackupSchedule_To_v1_MySQLBackupSchedule(in *mysql.MySQLBackupSchedule, out *MySQLBackupSchedule, s conversion.Scope) error {
	return autoConvert_mysql_MySQLBackupSchedule_To_v1_MySQLBackupSchedule(in, out, s)
}

func autoConvert_v1_MySQLBackupScheduleList_To_mysql_MySQLBackupScheduleList(in *MySQLBackupScheduleList, out *mysql.MySQLBackupScheduleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]mysql.MySQLBackupSchedule)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_MySQLBackupScheduleList_To_mysql_MySQLBackupScheduleList is an autogenerated conversion function.
func Convert_v1_MySQLBackupScheduleList_To_mysql_MySQLBackupScheduleList(in *MySQLBackupScheduleList, out *mysql.MySQLBackupScheduleList, s conversion.Scope) error {
	return autoConvert_v1_MySQLBackupScheduleList_To_mysql_MySQLBackupScheduleList(in, out, s)
}

func autoConvert_mysql_MySQLBackupScheduleList_To_v1_MySQLBackupScheduleList(in *mysql.MySQLBackupScheduleList, out *MySQLBackupScheduleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]MySQLBackupSchedule)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_mysql_MySQLBackupScheduleList_To_v1_MySQLBackupScheduleList is an autogenerated conversion function.
func Convert_mysql_MySQLBackupScheduleList_To_v1_MySQLBackupScheduleList(in *mysql.MySQLBackupScheduleList, out *MySQLBackupScheduleList, s conversion.Scope) error {
	return autoConvert_mysql_MySQLBackupScheduleList_To_v1_MySQLBackupScheduleList(in, out, s)
}

func autoConvert_v1_MySQLCluster_To_mysql_MySQLCluster(in *MySQLCluster, out *mysql.MySQLCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_MySQLClusterSpec_To_mysql_MySQLClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_MySQLClusterStatus_To_mysql_MySQLClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_MySQLCluster_To_mysql_MySQLCluster is an autogenerated conversion function.
func Convert_v1_MySQLCluster_To_mysql_MySQLCluster(in *MySQLCluster, out *mysql.MySQLCluster, s conversion.Scope) error {
	return autoConvert_v1_MySQLCluster_To_mysql_MySQLCluster(in, out, s)
}

func autoConvert_mysql_MySQLCluster_To_v1_MySQLCluster(in *mysql.MySQLCluster, out *MySQLCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_mysql_MySQLClusterSpec_To_v1_MySQLClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_mysql_MySQLClusterStatus_To_v1_MySQLClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_mysql_MySQLCluster_To_v1_MySQLCluster is an autogenerated conversion function.
func Convert_mysql_MySQLCluster_To_v1_MySQLCluster(in *mysql.MySQLCluster, out *MySQLCluster, s conversion.Scope) error {
	return autoConvert_mysql_MySQLCluster_To_v1_MySQLCluster(in, out, s)
}

func autoConvert_v1_MySQLClusterList_To_mysql_MySQLClusterList(in *MySQLClusterList, out *mysql.MySQLClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]mysql.MySQLCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_MySQLClusterList_To_mysql_MySQLClusterList is an autogenerated conversion function.
func Convert_v1_MySQLClusterList_To_mysql_MySQLClusterList(in *MySQLClusterList, out *mysql.MySQLClusterList, s conversion.Scope) error {
	return autoConvert_v1_MySQLClusterList_To_mysql_MySQLClusterList(in, out, s)
}

func autoConvert_mysql_MySQLClusterList_To_v1_MySQLClusterList(in *mysql.MySQLClusterList, out *MySQLClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]MySQLCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_mysql_MySQLClusterList_To_v1_MySQLClusterList is an autogenerated conversion function.
func Convert_mysql_MySQLClusterList_To_v1_MySQLClusterList(in *mysql.MySQLClusterList, out *MySQLClusterList, s conversion.Scope) error {
	return autoConvert_mysql_MySQLClusterList_To_v1_MySQLClusterList(in, out, s)
}

func autoConvert_v1_MySQLClusterSpec_To_mysql_MySQLClusterSpec(in *MySQLClusterSpec, out *mysql.MySQLClusterSpec, s conversion.Scope) error {
	out.Version = in.Version
	out.Replicas = in.Replicas
	out.MultiMaster = in.MultiMaster
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	out.Affinity = (*core_v1.Affinity)(unsafe.Pointer(in.Affinity))
	out.VolumeClaimTemplate = (*core_v1.PersistentVolumeClaim)(unsafe.Pointer(in.VolumeClaimTemplate))
	out.BackupVolumeClaimTemplate = (*core_v1.PersistentVolumeClaim)(unsafe.Pointer(in.BackupVolumeClaimTemplate))
	out.SecretRef = (*core_v1.LocalObjectReference)(unsafe.Pointer(in.SecretRef))
	out.ConfigRef = (*core_v1.LocalObjectReference)(unsafe.Pointer(in.ConfigRef))
	return nil
}

// Convert_v1_MySQLClusterSpec_To_mysql_MySQLClusterSpec is an autogenerated conversion function.
func Convert_v1_MySQLClusterSpec_To_mysql_MySQLClusterSpec(in *MySQLClusterSpec, out *mysql.MySQLClusterSpec, s conversion.Scope) error {
	return autoConvert_v1_MySQLClusterSpec_To_mysql_MySQLClusterSpec(in, out, s)
}

func autoConvert_mysql_MySQLClusterSpec_To_v1_MySQLClusterSpec(in *mysql.MySQLClusterSpec, out *MySQLClusterSpec, s conversion.Scope) error {
	out.Version = in.Version
	out.Replicas = in.Replicas
	out.MultiMaster = in.MultiMaster
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	out.Affinity = (*core_v1.Affinity)(unsafe.Pointer(in.Affinity))
	out.VolumeClaimTemplate = (*core_v1.PersistentVolumeClaim)(unsafe.Pointer(in.VolumeClaimTemplate))
	out.BackupVolumeClaimTemplate = (*core_v1.PersistentVolumeClaim)(unsafe.Pointer(in.BackupVolumeClaimTemplate))
	out.SecretRef = (*core_v1.LocalObjectReference)(unsafe.Pointer(in.SecretRef))
	out.ConfigRef = (*core_v1.LocalObjectReference)(unsafe.Pointer(in.ConfigRef))
	return nil
}

// Convert_mysql_MySQLClusterSpec_To_v1_MySQLClusterSpec is an autogenerated conversion function.
func Convert_mysql_MySQLClusterSpec_To_v1_MySQLClusterSpec(in *mysql.MySQLClusterSpec, out *MySQLClusterSpec, s conversion.Scope) error {
	return autoConvert_mysql_MySQLClusterSpec_To_v1_MySQLClusterSpec(in, out, s)
}

func autoConvert_v1_MySQLClusterStatus_To_mysql_MySQLClusterStatus(in *MySQLClusterStatus, out *mysql.MySQLClusterStatus, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Phase = mysql.MySQLClusterPhase(in.Phase)
	out.Errors = *(*[]string)(unsafe.Pointer(&in.Errors))
	return nil
}

// Convert_v1_MySQLClusterStatus_To_mysql_MySQLClusterStatus is an autogenerated conversion function.
func Convert_v1_MySQLClusterStatus_To_mysql_MySQLClusterStatus(in *MySQLClusterStatus, out *mysql.MySQLClusterStatus, s conversion.Scope) error {
	return autoConvert_v1_MySQLClusterStatus_To_mysql_MySQLClusterStatus(in, out, s)
}

func autoConvert_mysql_MySQLClusterStatus_To_v1_MySQLClusterStatus(in *mysql.MySQLClusterStatus, out *MySQLClusterStatus, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Phase = MySQLClusterPhase(in.Phase)
	out.Errors = *(*[]string)(unsafe.Pointer(&in.Errors))
	return nil
}

// Convert_mysql_MySQLClusterStatus_To_v1_MySQLClusterStatus is an autogenerated conversion function.
func Convert_mysql_MySQLClusterStatus_To_v1_MySQLClusterStatus(in *mysql.MySQLClusterStatus, out *MySQLClusterStatus, s conversion.Scope) error {
	return autoConvert_mysql_MySQLClusterStatus_To_v1_MySQLClusterStatus(in, out, s)
}

func autoConvert_v1_MySQLRestore_To_mysql_MySQLRestore(in *MySQLRestore, out *mysql.MySQLRestore, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_RestoreSpec_To_mysql_RestoreSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_RestoreStatus_To_mysql_RestoreStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_MySQLRestore_To_mysql_MySQLRestore is an autogenerated conversion function.
func Convert_v1_MySQLRestore_To_mysql_MySQLRestore(in *MySQLRestore, out *mysql.MySQLRestore, s conversion.Scope) error {
	return autoConvert_v1_MySQLRestore_To_mysql_MySQLRestore(in, out, s)
}

func autoConvert_mysql_MySQLRestore_To_v1_MySQLRestore(in *mysql.MySQLRestore, out *MySQLRestore, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_mysql_RestoreSpec_To_v1_RestoreSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_mysql_RestoreStatus_To_v1_RestoreStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_mysql_MySQLRestore_To_v1_MySQLRestore is an autogenerated conversion function.
func Convert_mysql_MySQLRestore_To_v1_MySQLRestore(in *mysql.MySQLRestore, out *MySQLRestore, s conversion.Scope) error {
	return autoConvert_mysql_MySQLRestore_To_v1_MySQLRestore(in, out, s)
}

func autoConvert_v1_MySQLRestoreList_To_mysql_MySQLRestoreList(in *MySQLRestoreList, out *mysql.MySQLRestoreList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]mysql.MySQLRestore)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_MySQLRestoreList_To_mysql_MySQLRestoreList is an autogenerated conversion function.
func Convert_v1_MySQLRestoreList_To_mysql_MySQLRestoreList(in *MySQLRestoreList, out *mysql.MySQLRestoreList, s conversion.Scope) error {
	return autoConvert_v1_MySQLRestoreList_To_mysql_MySQLRestoreList(in, out, s)
}

func autoConvert_mysql_MySQLRestoreList_To_v1_MySQLRestoreList(in *mysql.MySQLRestoreList, out *MySQLRestoreList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]MySQLRestore)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_mysql_MySQLRestoreList_To_v1_MySQLRestoreList is an autogenerated conversion function.
func Convert_mysql_MySQLRestoreList_To_v1_MySQLRestoreList(in *mysql.MySQLRestoreList, out *MySQLRestoreList, s conversion.Scope) error {
	return autoConvert_mysql_MySQLRestoreList_To_v1_MySQLRestoreList(in, out, s)
}

func autoConvert_v1_RestoreSpec_To_mysql_RestoreSpec(in *RestoreSpec, out *mysql.RestoreSpec, s conversion.Scope) error {
	out.ClusterRef = (*core_v1.LocalObjectReference)(unsafe.Pointer(in.ClusterRef))
	out.BackupRef = (*core_v1.LocalObjectReference)(unsafe.Pointer(in.BackupRef))
	out.AgentScheduled = in.AgentScheduled
	return nil
}

// Convert_v1_RestoreSpec_To_mysql_RestoreSpec is an autogenerated conversion function.
func Convert_v1_RestoreSpec_To_mysql_RestoreSpec(in *RestoreSpec, out *mysql.RestoreSpec, s conversion.Scope) error {
	return autoConvert_v1_RestoreSpec_To_mysql_RestoreSpec(in, out, s)
}

func autoConvert_mysql_RestoreSpec_To_v1_RestoreSpec(in *mysql.RestoreSpec, out *RestoreSpec, s conversion.Scope) error {
	out.ClusterRef = (*core_v1.LocalObjectReference)(unsafe.Pointer(in.ClusterRef))
	out.BackupRef = (*core_v1.LocalObjectReference)(unsafe.Pointer(in.BackupRef))
	out.AgentScheduled = in.AgentScheduled
	return nil
}

// Convert_mysql_RestoreSpec_To_v1_RestoreSpec is an autogenerated conversion function.
func Convert_mysql_RestoreSpec_To_v1_RestoreSpec(in *mysql.RestoreSpec, out *RestoreSpec, s conversion.Scope) error {
	return autoConvert_mysql_RestoreSpec_To_v1_RestoreSpec(in, out, s)
}

func autoConvert_v1_RestoreStatus_To_mysql_RestoreStatus(in *RestoreStatus, out *mysql.RestoreStatus, s conversion.Scope) error {
	out.Phase = mysql.RestorePhase(in.Phase)
	out.TimeStarted = in.TimeStarted
	out.TimeCompleted = in.TimeCompleted
	return nil
}

// Convert_v1_RestoreStatus_To_mysql_RestoreStatus is an autogenerated conversion function.
func Convert_v1_RestoreStatus_To_mysql_RestoreStatus(in *RestoreStatus, out *mysql.RestoreStatus, s conversion.Scope) error {
	return autoConvert_v1_RestoreStatus_To_mysql_RestoreStatus(in, out, s)
}

func autoConvert_mysql_RestoreStatus_To_v1_RestoreStatus(in *mysql.RestoreStatus, out *RestoreStatus, s conversion.Scope) error {
	out.Phase = RestorePhase(in.Phase)
	out.TimeStarted = in.TimeStarted
	out.TimeCompleted = in.TimeCompleted
	return nil
}

// Convert_mysql_RestoreStatus_To_v1_RestoreStatus is an autogenerated conversion function.
func Convert_mysql_RestoreStatus_To_v1_RestoreStatus(in *mysql.RestoreStatus, out *RestoreStatus, s conversion.Scope) error {
	return autoConvert_mysql_RestoreStatus_To_v1_RestoreStatus(in, out, s)
}

func autoConvert_v1_ScheduleStatus_To_mysql_ScheduleStatus(in *ScheduleStatus, out *mysql.ScheduleStatus, s conversion.Scope) error {
	out.Phase = mysql.BackupSchedulePhase(in.Phase)
	out.LastBackup = in.LastBackup
	return nil
}

// Convert_v1_ScheduleStatus_To_mysql_ScheduleStatus is an autogenerated conversion function.
func Convert_v1_ScheduleStatus_To_mysql_ScheduleStatus(in *ScheduleStatus, out *mysql.ScheduleStatus, s conversion.Scope) error {
	return autoConvert_v1_ScheduleStatus_To_mysql_ScheduleStatus(in, out, s)
}

func autoConvert_mysql_ScheduleStatus_To_v1_ScheduleStatus(in *mysql.ScheduleStatus, out *ScheduleStatus, s conversion.Scope) error {
	out.Phase = BackupSchedulePhase(in.Phase)
	out.LastBackup = in.LastBackup
	return nil
}

// Convert_mysql_ScheduleStatus_To_v1_ScheduleStatus is an autogenerated conversion function.
func Convert_mysql_ScheduleStatus_To_v1_ScheduleStatus(in *mysql.ScheduleStatus, out *ScheduleStatus, s conversion.Scope) error {
	return autoConvert_mysql_ScheduleStatus_To_v1_ScheduleStatus(in, out, s)
}

func autoConvert_v1_Storage_To_mysql_Storage(in *Storage, out *mysql.Storage, s conversion.Scope) error {
	out.Provider = in.Provider
	out.SecretRef = (*core_v1.LocalObjectReference)(unsafe.Pointer(in.SecretRef))
	out.Config = *(*map[string]string)(unsafe.Pointer(&in.Config))
	return nil
}

// Convert_v1_Storage_To_mysql_Storage is an autogenerated conversion function.
func Convert_v1_Storage_To_mysql_Storage(in *Storage, out *mysql.Storage, s conversion.Scope) error {
	return autoConvert_v1_Storage_To_mysql_Storage(in, out, s)
}

func autoConvert_mysql_Storage_To_v1_Storage(in *mysql.Storage, out *Storage, s conversion.Scope) error {
	out.Provider = in.Provider
	out.SecretRef = (*core_v1.LocalObjectReference)(unsafe.Pointer(in.SecretRef))
	out.Config = *(*map[string]string)(unsafe.Pointer(&in.Config))
	return nil
}

// Convert_mysql_Storage_To_v1_Storage is an autogenerated conversion function.
func Convert_mysql_Storage_To_v1_Storage(in *mysql.Storage, out *Storage, s conversion.Scope) error {
	return autoConvert_mysql_Storage_To_v1_Storage(in, out, s)
}
