apiVersion: v1
kind: Secret
metadata:
  name: mysql-ssl-secret
type: Opaque
data:
  ca.crt: <base64'd Root CA certificate>
  tls.crt: <base64'd server certificate>
  tls.key:  <base64'd server private key>
