---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-operator
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlclusters.mysql.oracle.com
spec:
  group: mysql.oracle.com
  version: v1
  scope: Namespaced
  names:
    kind: MySQLCluster
    singular: mysqlcluster
    plural: mysqlclusters
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlbackups.mysql.oracle.com
spec:
  group: mysql.oracle.com
  version: v1
  scope: Namespaced
  names:
    kind: MySQLBackup
    singular: mysqlbackup
    plural: mysqlbackups
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlrestores.mysql.oracle.com
spec:
  group: mysql.oracle.com
  version: v1
  scope: Namespaced
  names:
    kind: MySQLRestore
    singular: mysqlrestore
    plural: mysqlrestores
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlbackupschedules.mysql.oracle.com
spec:
  group: mysql.oracle.com
  version: v1
  scope: Namespaced
  names:
    kind: MySQLBackupSchedule
    singular: mysqlbackupschedule
    plural: mysqlbackupschedules
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator
  namespace: mysql-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-agent
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: mysql-operator
  namespace: mysql-operator
rules:
  - apiGroups:
    - mysql.oracle.com
    resources:
    - mysqlclusters
    - mysqlbackups
    - mysqlbackupschedules
    - mysqlrestores
    verbs: ["*"]
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - create
    - delete
  - apiGroups:
    - apps
    resources:
    - statefulsets
    verbs:
    - get
    - list
    - watch
    - patch
    - create
    - update
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - update
    - patch
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - get
    - list
    - watch
    - create
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: mysql-operator
  namespace: mysql-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:  ClusterRole
  name: mysql-operator
subjects:
- kind: ServiceAccount
  name: mysql-operator
  namespace: mysql-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mysql-agent
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mysql-operator
subjects:
- kind: ServiceAccount
  name: mysql-agent
  namespace: default
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: mysql-operator
  labels:
    app: mysql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: mysql-operator
      containers:
      - name: mysql-operator-controller
        image: iad.ocir.io/oracle/mysql-operator:0.1.0
        env:
        - name: MYSQL_AGENT_VERSION
          value: 0.1.0
        ports:
        - containerPort: 10254
        args:
          - --v=4
